deploymentName: frontend
replicaCount: 2

image:
  repository: 179235553979.dkr.ecr.us-east-1.amazonaws.com/frontend
  tag: latest
  pullPolicy: Always

service:
  name: frontend-service
  type: LoadBalancer
  port: 80

labels:
  app: frontend
