apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-{{ .Values.slot }}
  labels:
    app: auth-service
    slot: {{ .Values.slot }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
      slot: {{ .Values.slot }}
  template:
    metadata:
      labels:
        app: auth-service
        slot: {{ .Values.slot }}
    spec:
      containers:
      - name: auth-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
