apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 179235553979.dkr.ecr.us-east-1.amazonaws.com/auth:${TAG}
          ports:
            - containerPort: 5000