name: QA Build

on:
  workflow_dispatch:  # manual trigger
  workflow_run:
    workflows: ["Nighlty Build"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{env.AWS_SESSION_TOKEN}}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      - name: Install kubectl
        run: |
          KUBECTL_VERSION=$(curl -sL https://dl.k8s.io/release/stable.txt)
          echo "Fetched KUBECTL_VERSION=$KUBECTL_VERSION"
          curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client
        
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name EKS-Cluster

      - name: Creates Namespace
        run: |
          bash scripts/create_namespace.sh qa

      - name: Deploy services to EKS
        run: |
          bash scripts/deploy_services.sh qa

      - name: Test Deployment to QA
        run: |
          bash scripts/test_deployment.sh qa frontend-service
      
      # - name: Promote QA Images to Latest
      #   run: |
      #     bash scripts/promote_batch.sh qa blue
      
      - name: Promote Nightly Images to production
        run: |
          bash scripts/promote_production.sh $AWS_ACCOUNT_ID qa

      - name: Cleanup qa Namespace
        run: |
          bash scripts/clean_up.sh qa
