name: Setup Monitoring on EKS

on:
  workflow_dispatch:

jobs:
  setup-monitoring:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CLUSTER_NAME: EKS-Cluster

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        run: |
          KUBECTL_VERSION=$(curl -sL https://dl.k8s.io/release/stable.txt)
          echo "Fetched KUBECTL_VERSION=$KUBECTL_VERSION"
          curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Add Prometheus Helm Repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Create Monitoring Namespace
        run: |
          kubectl create namespace monitoring || echo "Already exists"

      - name: Install kube-prometheus-stack
        run: |
          helm install monitoring prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --wait

      - name: Print Grafana Password
        run: |
          echo "Grafana login (username: admin)"
          kubectl get secret --namespace monitoring monitoring-grafana \
            -o jsonpath="{.data.admin-password}" | base64 --decode && echo ""

      - name: Print Port Forward Instructions
        run: |
          echo "Run this locally to access Grafana UI:"
          echo "kubectl port-forward svc/monitoring-grafana 3001:80 -n monitoring"
